Client with Java 8 runtime and Apache HttpClient 5 Transport fails with java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer (#920)
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
(cherry picked from commit 0db2215c54f98e7b76c9cf4e1dd27056fd415c3d)
Signed-off-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>